name: franka_kitchen

task_name: ${name}

shape_meta: &shape_meta
  obs:
    point_cloud:
      shape: [512, 3]
      type: point_cloud
    agent_pos:
      shape: [9]
      type: low_dim
  action:
    shape: [9]

env_runner:
  _target_: flow_policy_3d.env_runner.franka_kitchen_runner.FrankaKitchenRunner
  eval_episodes: 20
  max_steps: 280
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  device: ${training.device}
  use_point_crop: ${policy.use_point_crop}
  num_points: 512
  env_name: kitchen-complete-v0

dataset:
  _target_: flow_policy_3d.dataset.franka_kitchen_dataset.FrankaKitchenDataset
  # Set absolute path on each machine, e.g. vast.ai: task.dataset.zarr_path=/workspace/FlowPolicy/data/...
  zarr_path: /home/dafa/Documents/FlowPolicy/data/franka_kitchen_expert.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
  augment: false
  pc_noise_std: 0.0
  pc_point_dropout_ratio: 0.0
  agent_pos_noise_std: 0.0
